# Generated by Django 5.2 on 2025-04-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_itinerarysection_itineraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='OVERVIEW', max_length=100)),
                ('intro_paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OverviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.overviewsection')),
            ],
        ),
        migrations.CreateModel(
            name='OverviewBulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='myapp.overviewsection')),
            ],
        ),
    ]
