# Generated by Django 5.2 on 2025-04-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_overviewsection_overviewdetail_overviewbulletpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('package_name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='packages/')),
                ('short_overview', models.CharField(max_length=250)),
                ('places_covering', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttractionBulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage')),
            ],
        ),
    ]
