# Generated by Django 5.2 on 2025-04-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_boatingpackage_attractionbulletpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_attraction', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage')),
            ],
        ),
    ]
