# Generated by Django 5.2 on 2025-04-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mainattraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarysection',
            name='heading',
        ),
        migrations.AddField(
            model_name='itinerarysection',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='itinerarysection',
            name='short_description',
            field=models.TextField(default='ITENERARY'),
        ),
    ]
