# Generated by Django 5.2 on 2025-04-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_itinerarysection_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overviewbulletpoint',
            name='section',
        ),
        migrations.RemoveField(
            model_name='overviewdetail',
            name='section',
        ),
        migrations.AlterField(
            model_name='itinerarysection',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FoodStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_style', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
        migrations.DeleteModel(
            name='OverviewBulletPoint',
        ),
        migrations.DeleteModel(
            name='OverviewDetail',
        ),
        migrations.DeleteModel(
            name='OverviewSection',
        ),
    ]
