# Generated by Django 5.2 on 2025-04-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_overviewbulletpoint_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('food', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodtiming', to='myapp.boatingpackage')),
            ],
        ),
    ]
