# Generated by Django 5.2 on 2025-04-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_whendoesitrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage')),
            ],
        ),
    ]
