# Generated by Django 5.2 on 2025-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='end_time',
            field=models.CharField(default='5:00 PM', max_length=300),
        ),
        migrations.AddField(
            model_name='duration',
            name='start_time',
            field=models.CharField(default='10:00 AM', max_length=300),
        ),
    ]
