# Generated by Django 5.2 on 2025-04-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_duration_end_time_duration_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartAndEndPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.TextField()),
                ('ending_point', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boatingpackage')),
            ],
        ),
    ]
