# Generated by Django 5.2 on 2025-04-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_goodtoknow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='attractionbulletpoint',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_bullet_points', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='foodbulletpoint',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_bullet_points', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='foodstyle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_styles', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='goodtoknow',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodtoknow', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='itinerarysection',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_desc', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='mainattraction',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_attraction', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='startandendpoints',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_end_points', to='myapp.boatingpackage'),
        ),
        migrations.AlterField(
            model_name='whendoesitrun',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='myapp.boatingpackage'),
        ),
    ]
