# Generated by Django 5.2 on 2025-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_boat_alter_attractionbulletpoint_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='image',
            field=models.ImageField(default=1, upload_to='bots/'),
        ),
    ]
