# Generated by Django 5.2 on 2025-04-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_boat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='video_link',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
