# Generated by Django 5.2 on 2025-04-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_boat_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDistrictAndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=355)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='myapp.boat')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
    ]
