# Generated by Django 5.2 on 2025-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_aboutdistrictandservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='short_desc',
            field=models.TextField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='boat',
            name='video_link',
            field=models.CharField(default=1, max_length=1255),
        ),
    ]
