# Generated by Django 5.2 on 2025-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_boat_short_desc_alter_boat_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdistrictandservice',
            name='about',
            field=models.TextField(),
        ),
    ]
