# Generated by Django 5.2 on 2025-04-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_aboutdistrictandservice_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_tour_place', models.TextField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_about', to='myapp.boat')),
            ],
        ),
    ]
