# Generated by Django 5.2 on 2025-04-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_tourpackagessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_faq', to='myapp.boat')),
            ],
        ),
    ]
