# Generated by Django 5.2 on 2025-04-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_boatfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatingpackage',
            name='boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='myapp.boat'),
        ),
    ]
