# Generated by Django 5.2 on 2025-05-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_contacts_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='guests',
        ),
        migrations.AddField(
            model_name='contacts',
            name='package_type',
            field=models.CharField(choices=[('family', 'Family Package'), ('adventure', 'Adventure Package'), ('luxury', 'Luxury Package'), ('honeymoon', 'Honeymoon Package')], default='family', max_length=20),
        ),
    ]
