# Generated by Django 5.1 on 2025-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_contacts_check_in_remove_contacts_check_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='property/')),
                ('short_desc', models.TextField(max_length=1255)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='package_type',
            field=models.CharField(choices=[('boat', 'Boating Package'), ('Home stay', 'Home Stays')], default='boat', max_length=20),
        ),
    ]
