# Generated by Django 5.1 on 2025-05-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_property_alter_contacts_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Property/')),
                ('heading', models.CharField(max_length=250)),
                ('bullet_point_heading', models.CharField(max_length=250)),
                ('bullet_points', models.CharField(max_length=1000)),
                ('short_desc', models.TextField()),
                ('welcome', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.property')),
            ],
        ),
    ]
