# Generated by Django 5.1 on 2025-05-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_propertydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='bullet_points',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='welcome',
        ),
        migrations.CreateModel(
            name='PropertyDetailsBulletPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_points', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_bullets', to='myapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRemaingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField()),
                ('welcome', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_remaining', to='myapp.property')),
            ],
        ),
    ]
