# Generated by Django 5.1 on 2025-05-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_thumbnailimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.property')),
            ],
        ),
    ]
