# Generated by Django 5.1 on 2025-05-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_propertyamenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartYourLuxuriousSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='property/')),
                ('short_desc', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury', to='myapp.property')),
            ],
        ),
    ]
