# Generated by Django 5.2 on 2025-05-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_startyourluxurioussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDiningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining', to='myapp.property')),
            ],
        ),
    ]
