# Generated by Django 5.2 on 2025-05-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_propertydiningsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=350)),
                ('guest_words', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='myapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='property/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_section', to='myapp.property')),
            ],
        ),
    ]
