# Generated by Django 5.2 on 2025-05-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_propertytestimonial_propertytestimonialsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=300)),
                ('why_choose_place', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover', to='myapp.property')),
            ],
        ),
    ]
