# Generated by Django 5.2 on 2025-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_discoversection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(default='Bruno', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(default='Mars', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property/'),
        ),
    ]
